[build]
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[functions]
  included_files = [
    "netlify/functions/Servicios.xlsx",
    "netlify/functions/Clientes.xlsx",
    "public/plantilla_boleta.html"
  ]

  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]
